### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TeamDDG** [Avicus/Atlas#1]
is it Possible to download this into a jar while using Maven ?

**Comment by thekeenant** [comment]
It isn't available in a repo currently, don't think so.

**Comment by thekeenant** [comment]
It is now!

**Comment by TeamDDG** [comment]
K Nice!

**Comment by TeamDDG** [comment]
Kylo, 
i got an Error

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project atlas: .git directory coul

**Comment by TeamDDG** [comment]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project atlas: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by thekeenant** [comment]
You have to clone the repository as opposed to downloading it as a zip archive. @TeamDDG

**Comment by thekeenant** [comment]
Actually, I just pushed a fix that should make it work without git installed in the repo. Download and try again!

**Comment by TeamDDG** [comment]
and where do i need to add the Maps folder ?

**Comment by thekeenant** [comment]
Same directory as the server, as specified in config.yml

Here's a test map:
https://www.mediafire.com/?csmwocbmvg3kjtu

**Comment by TeamDDG** [comment]
the map is starting etc
but i think its broken
1, No scoreboard
2, When Breaking Monument it doesnt say in Chat (Only Console Chat » [22:46:36 INFO]: <MonumentObjective> Red Team Right completion = 0.0

**Comment by TeamDDG** [comment]
and on Axis you cant use the signs

**Comment by thekeenant** [comment]
Hence why I said "If you're looking to use the plugin for running a match right now, it won't work. Atlas isn't near completion currently."
