### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TeamDDG** [Avicus/Atlas#5]
Hey, Kylo can you pm me when this is Workig good?

**Comment by AustinLMayes** [comment]
@TeamDDG just subscribe to the repository.

**Comment by TeamDDG** [comment]
how? @AustinLMayes

**Comment by thekeenant** [comment]
![2016-02-23 15_56_16-question issue 5 avicus_atlas](https://cloud.githubusercontent.com/assets/1189775/13268072/fdfd5156-da45-11e5-9ffe-70301043b5fc.png)
